Update watchdog_mbim_script

diff --git a/watchdog_mbim_script b/watchdog_mbim_script
--- a/watchdog_mbim_script
+++ b/watchdog_mbim_script
@@ -17,7 +17,8 @@ get_uptime_s()
         case "${__uptime}" in
                 ''|*[!0-9]*) false ;;
                 *) :
-        esac || { reg_failure "Failed to get uptime from /proc/uptime."; eval "${1}"=0; return 1; }
+        #esac || { reg_failure "Failed to get uptime from /proc/uptime."; eval "${1}"=0; return 1; }
+        esac || { logger "exec: /root/watchdog_mbim: Failed to get uptime from /proc/uptime."; exit 1 }
         eval "${1}"='${__uptime:-0}'
 }
 
@@ -83,5 +84,5 @@ while true; do
 
 done
 
-exit 0
+#exit 0
 
